source = /home/hexdev/.config/hypr/hyprland/monitors.conf
source = /home/hexdev/.config/hypr/hyprland/inputs.conf
source = /home/hexdev/.config/hypr/hyprland/keybinds.conf
source = /home/hexdev/.config/hypr/hyprland/autostart.conf
source = /home/hexdev/.config/hypr/hyprland/appearance.conf
