background {
	path=/home/hexdev/.wallpapers/lock.png
	blur_passes=1
}

label {
	monitor = HDMI-A-1
	text = cmd[update:0] ~/.scripts/greeting.sh
	color = rgba(200, 200, 200, 1.0)
	font_size = 18
	font_family = Montserrat Light Italic 
	position = 0,20
	halign = center
	valign = bottom 
}
shape {
    monitor = HDMI-A-1
    size = 20, 20
    color = rgba(0, 0, 0, 0.0) # no fill
    rounding = -1 # circle
    border_size = 4
    border_color = rgba(255, 255, 255, 1.0)

    position = 0, 60
    halign = center
    valign = bottom
}

label {
	position = 0,40
	font_family = Montserrat Extrabold
	font_size = 64
	text = cmd[update:1000] echo $(date +"%H:%M") 
}

label {
	font_family = Montserrat Light
	position=0,-40
	font_size=24
	text = cmd[update:0] echo $(LC_TIME=C date +"%A, %d %B %Y")
}
