# ENV SHENANIGANS
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'

env = QT_QPA_PLATFORMTHEME, qt5ct
env = QT_QPA_PLATFORM,wayland;xcb
QT_QPA_PLATFORM=wayland flatpak run com.ayugram.desktop

# APPS
exec-once = waybar & hyprpaper & throne
