# ENV SHENANIGANS
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'

env = QT_QPA_PLATFORMTHEME, qt5ct
env = QT_QPA_PLATFORM,wayland;xcb
QT_QPA_PLATFORM=wayland flatpak run com.ayugram.desktop

# APPS
exec-once = waybar & hyprpaper & throne

# PROXIES
export http_proxy=http://127.0.0.1:2080
export https_proxy=http://127.0.0.1:2080
export no_proxy=.host1,.my.com,.local
# reuse values for another case
export HTTP_PROXY=${http_proxy}
export HTTPS_PROXY=${https_proxy}
export NO_PROXY=${no_proxy}